### ISSUE TITLE
I proved the ps_mul_assoc, its order should be like this: lemma ps_mul_assoc {p o : ℕ+} : ∀ (a b c : PieceState p o), ps_mul c (ps_mul b a) = ps_mul (ps_mul c b) a

### ISSUE THREAD

**Issue by chenjulang** [AlexDuchnowski/rubiks-cube#1]
Check this out:https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/.E2.9C.94.20Rubik's.20cube.20associative.20law.3F

In this file: "https://github.com/AlexDuchnowski/rubiks-cube/blob/main/RubiksCube/RubiksCubeFunc.lean"

lemma ps_mul_assoc {p o : ℕ+} :
∀ (a b c : PieceState p o),
ps_mul c (ps_mul b a) = ps_mul (ps_mul c b) a := by
  intro a b c
  simp [ps_mul]
  apply And.intro
  · simp [Perm.mul_def]
    simp [Equiv.trans_assoc]
  · rw [← add_assoc]
    simp only [add_left_inj]
    exact rfl
  done

**Comment by chenjulang** [comment]
The second parameter of "ps_mul" is actually the first Rubik's Cube operation performed.

**Comment by AlexDuchnowski** [comment]
Thanks for completing the proof of the second conjunct! I've updated the file to have the full proof.

When it comes to the order of the variables in the statement of the lemma, I'm pretty sure the statements are equivalent, since there are no particular assumptions made about any of the PieceStates. To transform one statement into the other, simply flip the sides of the equality and swap a and c. (Either way, the original lemma statement is proven with the proof you provided, so I kept it the same).

**Comment by chenjulang** [comment]
Doubts about "plus_mul":

How is the "orient" defined in a practical sense in "plus_mul"? Clockwise or counterclockwise? Which direction of edge block and corner block is 0,1,2?


julang
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AlexDuchnowski/rubiks-cube"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月20日(星期二) 凌晨4:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AlexDuchnowski/rubiks-cube] I proved the ps_mul_assoc, its order should be like this: lemma ps_mul_assoc {p o : ℕ+} : ∀ (a b c : PieceState p o), ps_mul c (ps_mul b a) = ps_mul (ps_mul c b) a (Issue #1)





 
Thanks for completing the proof of the second conjunct! I've updated the file to have the full proof.
 
When it comes to the order of the variables in the statement of the lemma, I'm pretty sure the statements are equivalent, since there are no particular assumptions made about any of the PieceStates. To transform one statement into the other, simply flip the sides of the equality and swap a and c. (Either way, the original lemma statement is proven with the proof you provided, so I kept it the same).
